// The compiler's built-in names and ARITIES, read from
// Types/Builtins.codex by ladder builtins_probe.py. A call to one of
// these is not an undefined name, and the arity is the shape of the
// declared type -- a FunTy spine, with ForAllTy, ForAllEff and
// EffectfulTy transparent -- so a function-typed argument does not
// inflate it.
//
// `Some(0)` IS NOT `None`. `Some(0)` is a builtin whose declared type
// is not an arrow -- `get-ticks : Integer` -- so a reference to it is a
// VALUE and not a function of one argument. `None` is one of the eight
// that declare no type at all. Re-run the probe after a pin change; do
// not edit by hand.
pub const BUILTINS: [(&str, Option<usize>); 265] = [
    ("negate", Some(1)),
    ("text-length", Some(1)),
    ("integer-to-text", Some(1)),
    ("char-at", Some(2)),
    ("char-to-text", Some(1)),
    ("char-encode", Some(1)),
    ("substring", Some(3)),
    ("is-letter", Some(1)),
    ("is-digit", Some(1)),
    ("is-whitespace", Some(1)),
    ("char-code", Some(1)),
    ("char-code-at", Some(2)),
    ("code-to-char", Some(1)),
    ("text-replace", Some(3)),
    ("text-to-double-bits", Some(1)),
    ("text-to-integer", Some(1)),
    ("show", Some(1)),
    ("compare", Some(2)),
    ("__dderiv-Show", Some(1)),
    ("__dderiv-Ord", Some(2)),
    ("print-line", Some(1)),
    ("print-line-raw", Some(1)),
    ("print-text", Some(1)),
    ("print-line-uni", Some(1)),
    ("print-uni", Some(1)),
    ("print-error", Some(1)),
    ("print-error-uni", Some(1)),
    ("list-length", Some(1)),
    ("list-insert-at", Some(3)),
    ("list-set-at", Some(3)),
    ("text-compare", Some(2)),
    ("list-snoc", Some(2)),
    ("list-push", Some(2)),
    ("list-at", Some(2)),
    ("tag-equal", Some(2)),
    ("__list-tail", Some(1)),
    ("__list-head", Some(1)),
    ("__list-len", Some(1)),
    ("read-line", Some(0)),
    ("read-line-cce", Some(0)),
    ("read-file-raw", Some(1)),
    ("read-serial-cce", Some(1)),
    ("read-file-uni", Some(1)),
    ("write-binary", Some(1)),
    ("write-binary-buf", Some(3)),
    ("external-compile-bare", Some(4)),
    ("text-split", Some(2)),
    ("text-contains", Some(2)),
    ("text-starts-with", Some(2)),
    ("get-args", Some(0)),
    ("get-env", Some(1)),
    ("current-dir", Some(0)),
    ("run-process", Some(2)),
    ("run-process-full", Some(2)),
    ("process-exit", Some(1)),
    ("fork", Some(1)),
    ("await", Some(1)),
    ("par", Some(2)),
    ("race", Some(1)),
    ("fail", Some(1)),
    ("run-state", Some(2)),
    ("get-state", Some(0)),
    ("set-state", Some(1)),
    ("block-read", Some(1)),
    ("block-write", Some(2)),
    ("block-read-sector", Some(1)),
    ("block-write-sector", Some(2)),
    ("peek-byte", Some(2)),
    ("poke-byte", Some(3)),
    ("port-in-byte", Some(1)),
    ("runtime-init", Some(1)),
    ("port-out-byte", Some(2)),
    ("port-in-32", Some(1)),
    ("port-out-32", Some(2)),
    ("gpu-in", Some(1)),
    ("gpu-out", Some(2)),
    ("gpu-mem-read", Some(2)),
    ("gpu-mem-write", Some(3)),
    ("port-in-16", Some(1)),
    ("port-out-16", Some(2)),
    ("port-in-16-block", Some(3)),
    ("port-out-16-block", Some(3)),
    ("flush-tlb", Some(0)),
    ("cpu-read-cr0", Some(0)),
    ("cpu-read-cr3", Some(0)),
    ("hosted-kind", Some(0)),
    ("cpu-cpuid-eax", Some(1)),
    ("cpu-cpuid-ebx", Some(1)),
    ("cpu-cpuid-ecx", Some(1)),
    ("cpu-cpuid-edx", Some(1)),
    ("peek-32", Some(2)),
    ("peek-16", Some(2)),
    ("peek-qword", Some(2)),
    ("poke-qword", Some(3)),
    ("poke-32", Some(3)),
    ("poke-16", Some(3)),
    ("read-mmio", Some(2)),
    ("poke-mmio", Some(3)),
    ("read-mmio-32", Some(2)),
    ("poke-mmio-32", Some(3)),
    ("alloc-bytes", Some(1)),
    ("block-select", Some(1)),
    ("block-sector-count", Some(0)),
    ("key-load", Some(1)),
    ("key-zero", Some(0)),
    ("key-status", Some(0)),
    ("process-yield", Some(0)),
    ("process-spawn", Some(1)),
    ("process-exit-self", Some(0)),
    ("process-spawn-priority", Some(3)),
    ("process-wait", Some(1)),
    ("get-ticks", Some(0)),
    ("process-get-pid", Some(0)),
    ("process-restrict-cap", Some(2)),
    ("chan-kern-create", Some(1)),
    ("chan-kern-send", Some(2)),
    ("chan-kern-recv", Some(1)),
    ("chan-kern-close", Some(1)),
    ("process-kill", Some(1)),
    ("process-get-cap", Some(1)),
    ("process-get-scope", Some(1)),
    ("process-set-scope", Some(2)),
    ("process-get-network-scope", Some(1)),
    ("process-set-network-scope", Some(2)),
    ("process-status", Some(1)),
    ("process-count", Some(0)),
    ("chan-kern-send-block", Some(2)),
    ("chan-kern-recv-block", Some(1)),
    ("chan-text-send", Some(2)),
    ("chan-text-recv", Some(1)),
    ("hardware-random", Some(0)),
    ("identity-whoami", Some(1)),
    ("identity-set", Some(2)),
    ("device-seed", Some(1)),
    ("boot-factstore-status", Some(0)),
    ("identity-set-proc", Some(3)),
    ("identity-get-proc", Some(2)),
    ("process-spawn-with-heap", Some(2)),
    ("process-spawn-on-core", Some(2)),
    ("net-status", Some(0)),
    ("net-get-hwaddr", Some(1)),
    ("net-send-raw", Some(2)),
    ("net-recv-raw", Some(1)),
    ("vmxon", Some(1)),
    ("vmclear", Some(1)),
    ("vmptrld", Some(1)),
    ("vmlaunch", Some(0)),
    ("vmresume", Some(0)),
    ("vmread", Some(1)),
    ("vmwrite", Some(2)),
    ("rdmsr", Some(1)),
    ("wrmsr", Some(2)),
    ("vmlaunch-full", Some(0)),
    ("vmresume-full", Some(0)),
    ("uefi-set-attr", Some(1)),
    ("uefi-clear-screen", Some(0)),
    ("uefi-set-cursor", Some(2)),
    ("uefi-enable-cursor", Some(1)),
    ("uefi-set-mode", Some(1)),
    ("uefi-read-key", Some(0)),
    ("uefi-read-key-ex", Some(0)),
    ("uefi-read-file", Some(1)),
    ("text-concat-list", Some(1)),
    ("raw-bytes-to-text", Some(1)),
    ("__linked-list-empty", Some(1)),
    ("__linked-list-push", Some(2)),
    ("__linked-list-to-list", Some(1)),
    ("__record-set", Some(3)),
    ("__heap-save", Some(0)),
    ("address-of", Some(1)),
    ("variant-tag", Some(1)),
    ("__self-type-defs", Some(0)),
    ("__heap-restore", Some(1)),
    ("__memset", Some(3)),
    ("__heap-advance", Some(1)),
    ("__deck-pos", Some(0)),
    ("__deck-set", Some(1)),
    ("__deck-alloc", Some(1)),
    ("__deck-enter", Some(0)),
    ("__deck-exit", Some(0)),
    ("__narrow", Some(1)),
    ("__list-with-capacity", Some(1)),
    ("__buf-write-byte", Some(3)),
    ("__buf-write-bytes", Some(3)),
    ("__buf-read-bytes", Some(3)),
    ("bit-and", Some(2)),
    ("bit-or", Some(2)),
    ("bit-xor", Some(2)),
    ("bit-shl", Some(2)),
    ("bit-shr", Some(2)),
    ("bit-shru", Some(2)),
    ("bit-not", Some(1)),
    ("int-mod", Some(2)),
    ("int-rem", Some(2)),
    ("abs", Some(1)),
    ("min", Some(2)),
    ("max", Some(2)),
    ("Refl", Some(0)),
    ("assume", Some(0)),
    ("sym", Some(1)),
    ("trans", Some(2)),
    ("cong", Some(1)),
    ("app-cong", Some(1)),
    ("prof-start", Some(1)),
    ("prof-dump", Some(1)),
    ("force", Some(1)),
    ("vec-splat", Some(1)),
    ("vec-extract", Some(2)),
    ("vec-add", Some(2)),
    ("vec-sub", Some(2)),
    ("vec-mul", Some(2)),
    ("vec-div", Some(2)),
    ("vec-reduce-add", Some(1)),
    ("vec-select", Some(3)),
    ("vec-load-at", Some(1)),
    ("vec-store-at", Some(2)),
    ("mask-any", Some(1)),
    ("mask-all", Some(1)),
    ("mask-none", Some(1)),
    ("mask-count", Some(1)),
    ("to-real-approx", Some(1)),
    ("from-real-approx", Some(1)),
    ("to-real-trapping", Some(1)),
    ("from-real-trapping", Some(1)),
    ("to-real-saturating", Some(1)),
    ("from-real-saturating", Some(1)),
    ("to-real-approx-trapping", Some(1)),
    ("from-real-approx-trapping", Some(1)),
    ("to-real-approx-saturating", Some(1)),
    ("from-real-approx-saturating", Some(1)),
    ("real-from-int", Some(1)),
    ("real-to-int", Some(1)),
    ("real-approx-from-int", Some(1)),
    ("real-approx-to-int", Some(1)),
    ("real-to-bits", Some(1)),
    ("bits-to-real", Some(1)),
    ("real-approx-to-bits", Some(1)),
    ("bits-to-real-approx", Some(1)),
    ("vec4-splat", Some(1)),
    ("vec4-extract", Some(2)),
    ("suggested-vector-width", Some(1)),
    ("atomic-load", Some(1)),
    ("atomic-store", Some(2)),
    ("atomic-cas", Some(3)),
    ("atomic-add", Some(2)),
    ("atomic-exchange", Some(2)),
    ("memory-fence", Some(1)),
    ("vec-empty", Some(0)),
    ("vec-singleton", Some(1)),
    ("vec-head", Some(1)),
    ("vec-cons", Some(2)),
    ("vec-length", Some(1)),
    ("s-new", Some(0)),
    ("s-send", Some(2)),
    ("s-recv", Some(1)),
    ("s-recv-value", Some(1)),
    ("s-close", Some(1)),
    ("True", None),
    ("False", None),
    ("Nothing", None),
    ("open-file", None),
    ("close-file", None),
    ("read-all", None),
    ("now", None),
    ("random-integer", None),
];
// The IR spelling of each builtin's declared type, read from
// Types/Builtins.codex by ladder builtins_probe.py --rust-types.
//
// A `(name "f" <type>)` node in emitted IR carries this. Only the
// builtins whose type this probe can render are here: a name ABSENT is a
// name the emitter must refuse, not one to default. A wrong type reads
// exactly like a right one until the byte-compare.
//
// Re-run the probe after a pin change; do not edit by hand.
pub const BUILTIN_IR_TYPES: [(&str, &str); 117] = [
    ("text-length", "(fn text int-default)"),
    ("integer-to-text", "(fn int-default text)"),
    ("char-at", "(fn text (fn int-default char))"),
    ("char-to-text", "(fn char text)"),
    ("char-encode", "(fn char text)"),
    ("substring", "(fn text (fn int-default (fn int-default text)))"),
    ("is-letter", "(fn char boolean)"),
    ("is-digit", "(fn char boolean)"),
    ("is-whitespace", "(fn char boolean)"),
    ("char-code", "(fn char int-default)"),
    ("char-code-at", "(fn text (fn int-default int-default))"),
    ("code-to-char", "(fn int-default char)"),
    ("text-replace", "(fn text (fn text (fn text text)))"),
    ("text-to-double-bits", "(fn text int-default)"),
    ("text-to-integer", "(fn text int-default)"),
    ("text-compare", "(fn text (fn text int-default))"),
    ("read-serial-cce", "(fn text text)"),
    ("write-binary-buf", "(fn int-default (fn int-default (fn int-default nothing)))"),
    ("text-contains", "(fn text (fn text boolean))"),
    ("text-starts-with", "(fn text (fn text boolean))"),
    ("current-dir", "text"),
    ("run-state", "(fn int-default (fn int-default int-default))"),
    ("get-state", "int-default"),
    ("set-state", "(fn int-default nothing)"),
    ("peek-byte", "(fn int-default (fn int-default int-default))"),
    ("poke-byte", "(fn int-default (fn int-default (fn int-default int-default)))"),
    ("flush-tlb", "int-default"),
    ("cpu-read-cr0", "int-default"),
    ("cpu-read-cr3", "int-default"),
    ("hosted-kind", "int-default"),
    ("cpu-cpuid-eax", "(fn int-default int-default)"),
    ("cpu-cpuid-ebx", "(fn int-default int-default)"),
    ("cpu-cpuid-ecx", "(fn int-default int-default)"),
    ("cpu-cpuid-edx", "(fn int-default int-default)"),
    ("peek-32", "(fn int-default (fn int-default int-default))"),
    ("peek-16", "(fn int-default (fn int-default int-default))"),
    ("peek-qword", "(fn int-default (fn int-default int-default))"),
    ("poke-qword", "(fn int-default (fn int-default (fn int-default int-default)))"),
    ("poke-32", "(fn int-default (fn int-default (fn int-default int-default)))"),
    ("poke-16", "(fn int-default (fn int-default (fn int-default int-default)))"),
    ("alloc-bytes", "(fn int-default int-default)"),
    ("block-sector-count", "int-default"),
    ("key-zero", "int-default"),
    ("key-status", "int-default"),
    ("process-yield", "int-default"),
    ("process-exit-self", "int-default"),
    ("process-wait", "(fn int-default int-default)"),
    ("get-ticks", "int-default"),
    ("process-get-pid", "int-default"),
    ("process-get-cap", "(fn int-default int-default)"),
    ("process-get-scope", "(fn int-default text)"),
    ("process-get-network-scope", "(fn int-default text)"),
    ("process-status", "(fn int-default int-default)"),
    ("process-count", "int-default"),
    ("hardware-random", "int-default"),
    ("boot-factstore-status", "int-default"),
    ("net-status", "int-default"),
    ("vmxon", "(fn int-default int-default)"),
    ("vmclear", "(fn int-default int-default)"),
    ("vmptrld", "(fn int-default int-default)"),
    ("vmlaunch", "int-default"),
    ("vmresume", "int-default"),
    ("vmread", "(fn int-default int-default)"),
    ("vmwrite", "(fn int-default (fn int-default int-default))"),
    ("rdmsr", "(fn int-default int-default)"),
    ("wrmsr", "(fn int-default (fn int-default int-default))"),
    ("vmlaunch-full", "int-default"),
    ("vmresume-full", "int-default"),
    ("uefi-set-attr", "(fn int-default int-default)"),
    ("uefi-clear-screen", "int-default"),
    ("uefi-set-cursor", "(fn int-default (fn int-default int-default))"),
    ("uefi-enable-cursor", "(fn int-default int-default)"),
    ("uefi-set-mode", "(fn int-default int-default)"),
    ("uefi-read-key", "int-default"),
    ("uefi-read-key-ex", "int-default"),
    ("uefi-read-file", "(fn text text)"),
    ("__heap-save", "int-default"),
    ("__heap-restore", "(fn int-default nothing)"),
    ("__memset", "(fn int-default (fn int-default (fn int-default nothing)))"),
    ("__heap-advance", "(fn int-default nothing)"),
    ("__deck-pos", "int-default"),
    ("__deck-set", "(fn int-default nothing)"),
    ("__deck-alloc", "(fn int-default int-default)"),
    ("__deck-enter", "nothing"),
    ("__deck-exit", "nothing"),
    ("__narrow", "(fn int-default int-default)"),
    ("__buf-write-byte", "(fn int-default (fn int-default (fn int-default int-default)))"),
    ("bit-and", "(fn int-default (fn int-default int-default))"),
    ("bit-or", "(fn int-default (fn int-default int-default))"),
    ("bit-xor", "(fn int-default (fn int-default int-default))"),
    ("bit-shl", "(fn int-default (fn int-default int-default))"),
    ("bit-shr", "(fn int-default (fn int-default int-default))"),
    ("bit-shru", "(fn int-default (fn int-default int-default))"),
    ("bit-not", "(fn int-default int-default)"),
    ("int-mod", "(fn int-default (fn int-default int-default))"),
    ("int-rem", "(fn int-default (fn int-default int-default))"),
    ("abs", "(fn int-default int-default)"),
    ("min", "(fn int-default (fn int-default int-default))"),
    ("max", "(fn int-default (fn int-default int-default))"),
    ("prof-start", "(fn int-default int-default)"),
    ("prof-dump", "(fn int-default int-default)"),
    ("to-real-approx", "(fn real real-approx)"),
    ("from-real-approx", "(fn real-approx real)"),
    ("real-from-int", "(fn int-default real)"),
    ("real-to-int", "(fn real int-default)"),
    ("real-approx-from-int", "(fn int-default real-approx)"),
    ("real-approx-to-int", "(fn real-approx int-default)"),
    ("real-to-bits", "(fn real int-default)"),
    ("bits-to-real", "(fn int-default real)"),
    ("real-approx-to-bits", "(fn real-approx int-default)"),
    ("bits-to-real-approx", "(fn int-default real-approx)"),
    ("atomic-load", "(fn int-default int-default)"),
    ("atomic-store", "(fn int-default (fn int-default int-default))"),
    ("atomic-cas", "(fn int-default (fn int-default (fn int-default boolean)))"),
    ("atomic-add", "(fn int-default (fn int-default int-default))"),
    ("atomic-exchange", "(fn int-default (fn int-default int-default))"),
    ("memory-fence", "(fn int-default int-default)"),
];
